server:
  port: 7999
  
spring:  application:    name: eureka-example

eureka:  client:    register-with-eureka: false
    fetch-registry: false
  server:
    wait-time-in-ms-when-sync-empty: 0  
    enable-self-preservation: false